### ISSUE TITLE
Python console input-ban nincs ellenőrzés

### ISSUE THREAD

**Issue by Lovasz-Akos** [Lovasz-Akos/AFP-PoiPoi-Weather-uni#23]
Bármit belehet írni konzolba amikor dátumot kér és érdekes módon kapok eredményt hülyeségre is.

![image](https://user-images.githubusercontent.com/55391231/142446118-f8d7cbe7-23f6-4f82-bcf4-8c8a74d3e790.png)

**Comment by Lovasz-Akos** [comment]
hozzáadtam @P1ft4 -t legalább lesz mit csinálnia

**Comment by CoopsyChild** [comment]
Persze, hogy kapsz 🤙 , ugye az évet alapból nem veszi számításba a dátum alapú jóslás, így az kilőve. A hónap az már érdekesebb, de az meg azért van, mert a dátumkód ugye egy sima szám (2021.11.22 = 1122) így oda végsősoron bármilyen számot beírhatsz, a gép fog vele tudni számolni, csak te nem fogod tudni mihez "kötni" az eredményt.

**Comment by Lovasz-Akos** [comment]
@P1ft4 ummmm

**Comment by Lovasz-Akos** [comment]
when?

**Comment by Lovasz-Akos** [comment]
done by @P1ft4
